# Generated by Django 4.0.4 on 2022-05-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_message_options_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.profile', unique=True, verbose_name='Профиль в Телеграме'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('last_fm_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.user')),
            ],
        ),
    ]
