# Generated by Django 4.0.4 on 2022-05-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_album_artist_track_tracksinreport_artistinreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumsinreport',
            name='scrobbles',
            field=models.IntegerField(default=0, verbose_name='Прослушиваний в отчёте'),
        ),
        migrations.AddField(
            model_name='artistinreport',
            name='scrobbles',
            field=models.IntegerField(default=0, verbose_name='Прослушиваний в отчёте'),
        ),
        migrations.AddField(
            model_name='tracksinreport',
            name='scrobbles',
            field=models.IntegerField(default=0, verbose_name='Прослушиваний в отчёте'),
        ),
    ]
