# Generated by Django 4.0.4 on 2022-05-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_albumsinreport_scrobbles_artistinreport_scrobbles_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ALbumsInReport',
            new_name='AlbumInReport',
        ),
        migrations.RenameModel(
            old_name='TracksInReport',
            new_name='TrackInReport',
        ),
    ]
